version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: charger
    volumes:
      - ./api/db/data:/var/lib/mysql
    restart: always

  api:
    build:
      context: "./backend"
    container_name: python-container
    restart: always
    volumes:
      - ./api:/app
    ports: 
      - "9001:9001"
    depends_on:
      - db

  web:
    build:
      context: "./frontend"
    container_name: react-container
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - api