# Generated by Django 3.2.25 on 2024-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_kanastra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('government_id', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_due_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
