# Generated by Django 3.2.25 on 2024-05-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_kanastra', '0002_auto_20240505_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charges',
            new_name='Charge',
        ),
    ]
