# Generated by Django 3.2.25 on 2024-05-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_kanastra', '0003_rename_charges_charge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge',
            new_name='Charges',
        ),
    ]
